name: Build Docker Image
on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  docker:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Log in to Docker Hub
      id: login-docker-hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image latest
      id: build-and-push-image-latest
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dylanninin/openresty:latest

